### ISSUE TITLE
Who can remotely control and help me get this APP running in Xcode, Carthage generates.FarmWorks error

### ISSUE THREAD

**Issue by Dennis19872020** [readium/mobile#13]
The TeamViewer ID of my computer is 969 917 950 Passcode: cw789V
Who can help me? I'm helpless

**Comment by llemeurfr** [comment]
Are you serious to give access to your computer like that?

**Comment by mickael-menu** [comment]
@Dennis19872020 We don't have the resources for offering that kind of support. I already asked you several times for more infos but you keep posting new issues.

https://github.com/readium/r2-testapp-swift/issues/374

Please follow up on a single issue, and through GitHub.

**Comment by Dennis19872020** [comment]
who can help me

**Comment by Dennis19872020** [comment]
I tried all the methods you mentioned, but still, generated XcFrameworks and got an error

**Comment by Truck3r** [comment]
The only workaround I have found for this, is to run Carthage _without_ the --use-xcframeworks option - and immediately afterwards run Carthage again _with_ --use-xcframeworks set.
`carthage bootstrap --platform ios`
`carthage bootstrap --platform ios --use-xcframeworks`
It seems like the way the external dependencies are added to Xcode relies on the old framework format being available in order to build properly.

I don't have a cleaner solution for this at the moment...

**Comment by mickael-menu** [comment]
@Truck3r Did you check using `develop`? The latest version `2.0.0-beta.1` is still using `.framework`, but `develop` is using `.xcframework`

**Comment by Truck3r** [comment]
I did not - I'll try to switch to develop and let you know how it works out 👍  thanks 🙂

**Comment by Truck3r** [comment]
@mickael-menu 
Using the develop branch solves the problem for me.
On minor issue though - I had to include CryptoSwift in the Cartfile in a peculiar way - specifying the branch name rather than the version number - otherwise, Carthage would checkout v0.6.0beta2, even though I declared == 1.3.2 as the version to use...

My Cartfile:
github "onevcat/Kingfisher" == 5.15.6
github "weichsel/ZIPFoundation" == 0.9.11
github "jdg/MBProgressHUD" == 1.2.0
github "stephencelis/SQLite.swift" == 0.12.2
github "edrlab/GCDWebServer" == 3.6.3
github "krzyzanowskim/CryptoSwift" "1.3.2"
github "cezheng/Fuzi" == 3.1.3
github "dexman/Minizip" == 1.4.0
github "scinfu/SwiftSoup" == 2.3.2

github "readium/r2-shared-swift" "develop"
github "readium/r2-streamer-swift" "develop"
github "readium/r2-navigator-swift" "develop"
github "readium/readium-opds-swift" "develop"

**Comment by mickael-menu** [comment]
Can you try with 1.3.8 instead? Check out the updated versions for all dependencies in `develop`: https://github.com/readium/r2-testapp-swift/blob/develop/Cartfile
